<a href="https://colab.research.google.com/github/bhanu151/statistical-learning-course-2026/blob/main/CSSL_02_python_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Python

In [3]:
print('Welcome to Python') #This is a print statement.

Welcome to Python


###Variables and expressions

In [6]:
a = 5    # This vairable stores an int
var1 = 10.0 # This stores a float
str_var = "Alex" # This stores a string.

In [7]:
a

5

In [8]:
var1

10.0

In [9]:
str_var

'Alex'

In [16]:
type(str_var) #type lists the datatype of the variable

str

In [17]:
num1 = 1
num2 = 3
num3 = num1/num2 # There's finite precision when it comes to floating point numbers.
num3

0.3333333333333333

In [18]:
y = var1+a # Adding an int and a float
y

15.0

###Operators

In [27]:
p = num1+num2 # Addition
q = num1-num2 # Subtraction
r = num1*num2 # Multiplication
s = num1/num2 # Division
t = num1//num2 # Integer division; Gives the dividend
u = num1%num2 #Gives the remainder
print(p,q,r,s,t,u)
print("The value of p is",p) # Old-fashioned way of combining strings and variables while printing.
print(f"The value of p is {p}") # Using f-strings

4 -2 3 0.3333333333333333 0 1
The value of p is 4
The value of p is 4


### Lists

In [28]:
int_list = [1, 2, 3, 4] #List of integers
float_list = [1.0, 2.5, 3.7, 5.5] # List of floats
str_list = ["a", "b", "c", "d"] # List of strings
mixed_list  = [1, 2.4, "a", p] # Mixed list containing elements of different datatypes

In [34]:
mixed_list

[1, 2.4, 'a', 4]

### Aggregate functions on lists

In [36]:
sum(int_list) #Gives the sum of all elements

10

In [37]:
len(float_list) # Gives the count of the number of elements in the list

4

In [39]:
sum(mixed_list) # Can lead to errors if there are different datatypes involved

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [40]:
sum(str_list)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [43]:
int_float_list = int_list + str_list # The '+' operator when used with lists does concentenation
int_float_list

[1, 2, 3, 4, 'a', 'b', 'c', 'd']

### Exercise - Calculate the average score of this class

In [54]:
scores = [65, 78, 30, 85]

In [55]:
average_score = sum(scores) / len(scores) # Calculate the average
max_score = max(scores) # Gives the maximum
min_score = min(scores) # Gives the minimum
print(f"The class average is {average_score}, and the the class highest is {max_score}")

The class average is 64.5, and the the class highest is 85


### Functions and if statements

In [60]:
def has_student_passed(score):
  """
  This is a multiline comment.
  This function takes the score and returns pass if
  the score is above 40.
  """
  if score >= 40:
    print("The student has passed the course.") # Gets executed when if condition evaluates to true
  else:
    print("The student has not passed the course.") # Gets executed when if condition evaluates to false
  return


### For loop

In [63]:
for s in scores:
  print(f"s={s},")
  has_student_passed(s)


s=65,
The student has passed the course.
s=78,
The student has passed the course.
s=30,
The student has not passed the course.
s=85,
The student has passed the course.


## Homework: Write a function to calculate grades and return the grade

In [64]:
# The function will look something like this

def get_grade(score):
  """
  This is a multiline comment.
  This function takes the score and returns the grade.
  """
  if score >= 40 and score <=50:
    return "E"
  elif score>50 and score<=60:
    return "D"
  elif score>60 and score<=100:
    return "A"
  return "U"

### Getting help

In [69]:
help(sum) # To get help on function definitions

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



### Dictionaries

In [78]:
# A dictionary is a data structure that does 1-1 mapping of key-value pairs
scores_dict = {"Alex":scores[0], "Nandini":scores[1], "Trusha":scores[2], "Mohammed":scores[3]}
scores_dict

{'Alex': 65, 'Nandini': 78, 'Trusha': 30, 'Mohammed': 85}

In [85]:
scores_dict.keys() # Gives the list of keys in the dictionary

dict_keys(['Alex', 'Nandini', 'Trusha', 'Mohammed'])

In [86]:
scores_dict.values() # Gives all the values of the dictionary

dict_values([65, 78, 30, 85])

In [84]:
for key, score in zip(scores_dict.keys(), scores_dict.values()):
  print(key, score)

Alex 65
Nandini 78
Trusha 30
Mohammed 85


## Homework:
* Use this dictionary along with the for loop to print the name and the score of the student.
* You can also try calculating the grade of each student inside the for block

## NUMPY

In [87]:
import numpy as np # Importing the numpy package

In [91]:
zeros_arr = np.zeros(10) # An array of 10 zeros
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [95]:
zeros_arr_int_2D = np.zeros(shape=(4,3), dtype=int) # A 2D array of zeros of datatype int
zeros_arr_int_2D

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [96]:
ones_arr = np.ones(10) # An array of 10 ones
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [100]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(f"First array is {arr1} and its type is {type(arr1)}") # arr1 is no longer a simple list; it is a numpy array
print(f"Second array is {arr2}")

First array is [1 2 3 4 5] and its type is <class 'numpy.ndarray'>
Second array is [ 6  7  8  9 10]


### Numpy array operations

In [103]:
add_arr= arr1 +arr2 # Adding numpy arrays leads to element-wise addition
add_arr

array([ 7,  9, 11, 13, 15])

In [105]:
sub_arr = arr1-arr2 #This is true for other operations such as multiplication and division as well
sub_arr

array([-5, -5, -5, -5, -5])